[[redirects]]
  from = "/api/*"
  to = "https://seu-backend-production.up.railway.app/api/:splat"
  status = 200

[build]
  base = "curriculo-inteligente"
  command = "npm run build"
  publish = "dist"